const PHRASE_HASH='8e3cd1825c295646a4ced084670385d296d1c6357fedd11cf1568daf7bd9366e'; const FINAL91_HASH='9400f1b21cb527d7fa3d3eabba93557a18ebe7a2ca4e471cfe5e4c5b4ca7f767';
const CODEX_OPEN_PROOF_HASH='d630a75a1f9f69594dd980cf605743eaac812756ad69cc52ff765b848e9e92b4';
async function sha(s){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function normFor(c,s){let v=String(s??'').trim();if(c.case!=='preserve')v=v.toUpperCase();return v.replace(/\s+/g,'')}
async function isOpen(){try{const p=localStorage.getItem('aleph_codex_open')||'';return /^[0-9a-f]{64}$/.test(p)&&await sha(p)===CODEX_OPEN_PROOF_HASH}catch(e){return false}}
async function readMark(c){try{const proof=localStorage.getItem('aleph_codex_'+c.n)||'';if(!/^[0-9a-f]{64}$/.test(proof)||await sha(proof)!==c.proofHash)return null;return String.fromCharCode(c.markMask ^ parseInt(proof.slice(0,2),16))}catch(e){return null}}
async function status(){let s='';for(const c of C)s+=(await readMark(c))||'?';return s}
function familyGroups(){const m={};for(const c of C)(m[c.family]??=[]).push(c);return m}
async function renderMap(){if(!await isOpen())return;const solved=await status(),groups=familyGroups();let html=`<div class="eyebrow">CODEX::OPEN</div><h1 class="level">54–91</h1><h2 class="title">Treinta y ocho formas de leer una señal</h2><p class="lead">54–90 son no lineales. Resuelve por familias o salta entre ellas. Cada nodo genera una marca verificable. El 91 exige las 37 pruebas válidas.</p><div class="terminal">solved=${solved.replace(/\?/g,'·')}\ncount=${[...solved].filter(x=>x!=='?').length}/37</div>`;for(const [fam,arr] of Object.entries(groups)){html+=`<h3 class="codex-family">${fam}</h3><div class="grid codex-grid">`;for(const c of arr){const done=(await readMark(c))?' ✓':'';html+=`<button class="ringcard codex-node" onclick="openChallenge(${c.n})" data-node="${c.n}"><b>${c.n}${done}</b><span>${c.title}</span></button>`}html+='</div>'}html+=`<div class="convergence"><div class="eyebrow">91</div><h2>7 × 13</h2><button onclick="open91()">INTENTAR ESTACIÓN 91</button></div>`;app.innerHTML=html}
function escapeHtml(s){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function openChallenge(n){const c=C.find(x=>x.n===n);if(!c)return;let assets='';if(c.asset){for(const a of c.asset.split('|')){if(a.endsWith('.wav'))assets+=`<audio controls preload="metadata" aria-label="audio del reto ${n}"><source src="${a}"></audio><div class="external"><a href="${a}" download>DESCARGAR AUDIO</a></div>`;else if(a.endsWith('.txt'))assets+=`<div class="external"><a href="${a}" target="_blank">ABRIR BITMAP</a></div>`;else assets+=`<img class="artifact" src="${a}" alt="artefacto visual del reto ${n}">`}}app.innerHTML=`<div class="eyebrow">CODEX::${c.family}</div><h1 class="level">${n}</h1><h2 class="title">${c.title}</h2><p class="lead">${c.lead}</p><div class="terminal">${escapeHtml(c.data)}</div>${assets}<div class="row"><label class="sr-only" for="ans">Respuesta del reto ${n}</label><input id="ans" autocomplete="off" placeholder="respuesta"><button onclick="solve(${n})">VERIFICAR</button></div><div id="result" class="result" aria-live="polite"></div>${c.hint?`<details class="hint"><summary>Pista</summary><p>${c.hint}</p></details>`:''}<div class="next"><button class="secondary" onclick="renderMap()">VOLVER AL CODEX</button></div>`;window.scrollTo(0,0)}
async function solve(n){const c=C.find(x=>x.n===n),w=normFor(c,ans.value),h=await sha(w);if(h!==c.hash){result.innerHTML='<span class="bad">La lectura no coincide.</span>';return}const proof=await sha(`ALEPH91:${n}:${w}`);try{localStorage.setItem('aleph_codex_'+n,proof)}catch(e){}const ch=String.fromCharCode(c.markMask ^ parseInt(proof.slice(0,2),16));result.innerHTML=`<div class="ok">CODEX::${n} RESUELTO // mark=${ch}</div><p class="lead">La marca solo es válida porque está ligada criptográficamente a esta solución.</p>`}
async function open91(){const s=await status();if(await sha(s)!==PHRASE_HASH){let k=[...s].filter(x=>x!=='?').length;app.innerHTML=`<div class="eyebrow">CODEX::91</div><h1 class="level">91</h1><h2 class="title">La esquina todavía no existe</h2><div class="terminal">54…90 = ${k}/37\n${s.replace(/\?/g,'·')}</div><p class="lead">Las 37 marcas deben provenir de pruebas válidas y formar una frase continua antes de construir la matriz.</p><button onclick="renderMap()">VOLVER</button>`;return}app.innerHTML=`<div class="eyebrow">CODEX::91 // META</div><h1 class="level">7×13</h1><h2 class="title">El espejo del 19</h2><div class="terminal">37 marks = ${s}\nGRID = 7 × 13 = 91</div><p class="lead">La retícula completa tiene 7 filas y 13 columnas. Dos proyecciones del mismo punto dan:</p><div class="terminal">x ≡ 5 (mod 7)\nx ≡ 6 (mod 13)\n0 &lt; x &lt; 91</div><p class="lead">Reconstruye x. El teorema chino del resto cierra el espejo.</p><div class="row"><label class="sr-only" for="a91">Valor de x</label><input id="a91" inputmode="numeric" placeholder="x"><button onclick="solve91()">CERRAR CODEX</button></div><div id="result" class="result" aria-live="polite"></div>`}
async function solve91(){const w=String(a91.value??'').trim().replace(/\s+/g,'');if(await sha(w)!==FINAL91_HASH){result.innerHTML='<span class="bad">Ese punto no satisface ambas proyecciones.</span>';return}const proof=await sha(`ALEPH91:91:${w}`);try{localStorage.setItem('aleph_codex_91',proof);localStorage.setItem('aleph_comedia_open',proof)}catch(e){}result.innerHTML='<div class="ok"><h2>91 ⇄ 19</h2><p>El espejo se cierra, pero aparece una arquitectura posterior al código.</p><button onclick="collapse91()">VER 91 PUNTOS</button> <a class="btn" href="../comedia/">ENTRAR EN COMEDIA 92→100</a></div>'}
function collapse91(){const ov=document.createElement('div');ov.id='aleph-collapse';ov.innerHTML='<div class="aleph-core"><div class="aleph-core-number">91</div><div class="aleph-core-text">7 × 13<br>19 ⇄ 91</div><div class="aleph-core-sub">TODOS LOS CÓDIGOS SON FORMAS DE MIRAR</div><button onclick="document.getElementById(\'aleph-collapse\').remove()">CERRAR EL ESPEJO</button></div>';for(let r=0;r<7;r++)for(let c=0;c<13;c++){const i=r*13+c+1,d=document.createElement('span');d.className='aleph-point';d.textContent=String(i).padStart(2,'0');d.style.setProperty('--x',(8+c*7.0)+'vw');d.style.setProperty('--y',(14+r*12.0)+'vh');d.style.setProperty('--delay',(i*7)+'ms');ov.appendChild(d)}document.body.appendChild(ov);window.dispatchEvent(new CustomEvent('aleph-collapse',{detail:{total:91}}))}
isOpen().then(ok=>{if(ok)renderMap()});
